services:
  db:
    image: docker.arvancloud.ir/postgres
    container_name: db
    environment:
      POSTGRES_DB: "forex_db"
      POSTGRES_USER: "arman"
      POSTGRES_PASSWORD: "somehardpassword"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data/
    networks:
      - djangonetwork

  web:
    container_name: web
    build: .
    command: sh entery.sh
    # volumes:
    #   - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - djangonetwork

volumes:
  dbdata:

networks:
  djangonetwork:
    driver: bridge